export const countries = [
  { code: "AF", dial_code: "+93", flag: "🇦🇫", name: "Afghanistan" },
  { code: "AL", dial_code: "+355", flag: "🇦🇱", name: "Albania" },
  { code: "DZ", dial_code: "+213", flag: "🇩🇿", name: "Algeria" },
  { code: "AR", dial_code: "+54", flag: "🇦🇷", name: "Argentina" },
  { code: "AU", dial_code: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "AT", dial_code: "+43", flag: "🇦🇹", name: "Austria" },
  { code: "BD", dial_code: "+880", flag: "🇧🇩", name: "Bangladesh" },
  { code: "BE", dial_code: "+32", flag: "🇧🇪", name: "Belgium" },
  { code: "BR", dial_code: "+55", flag: "🇧🇷", name: "Brazil" },
  { code: "BG", dial_code: "+359", flag: "🇧🇬", name: "Bulgaria" },
  { code: "CA", dial_code: "+1", flag: "🇨🇦", name: "Canada" },
  { code: "CL", dial_code: "+56", flag: "🇨🇱", name: "Chile" },
  { code: "CN", dial_code: "+86", flag: "🇨🇳", name: "China" },
  { code: "CO", dial_code: "+57", flag: "🇨🇴", name: "Colombia" },
  { code: "HR", dial_code: "+385", flag: "🇭🇷", name: "Croatia" },
  { code: "CZ", dial_code: "+420", flag: "🇨🇿", name: "Czech Republic" },
  { code: "DK", dial_code: "+45", flag: "🇩🇰", name: "Denmark" },
  { code: "EG", dial_code: "+20", flag: "🇪🇬", name: "Egypt" },
  { code: "EE", dial_code: "+372", flag: "🇪🇪", name: "Estonia" },
  { code: "FI", dial_code: "+358", flag: "🇫🇮", name: "Finland" },
  { code: "FR", dial_code: "+33", flag: "🇫🇷", name: "France" },
  { code: "DE", dial_code: "+49", flag: "🇩🇪", name: "Germany" },
  { code: "GR", dial_code: "+30", flag: "🇬🇷", name: "Greece" },
  { code: "HK", dial_code: "+852", flag: "🇭🇰", name: "Hong Kong" },
  { code: "HU", dial_code: "+36", flag: "🇭🇺", name: "Hungary" },
  { code: "IS", dial_code: "+354", flag: "🇮🇸", name: "Iceland" },
  { code: "IN", dial_code: "+91", flag: "🇮🇳", name: "India" },
  { code: "ID", dial_code: "+62", flag: "🇮🇩", name: "Indonesia" },
  { code: "IE", dial_code: "+353", flag: "🇮🇪", name: "Ireland" },
  { code: "IL", dial_code: "+972", flag: "🇮🇱", name: "Israel" },
  { code: "IT", dial_code: "+39", flag: "🇮🇹", name: "Italy" },
  { code: "JP", dial_code: "+81", flag: "🇯🇵", name: "Japan" },
  { code: "KE", dial_code: "+254", flag: "🇰🇪", name: "Kenya" },
  { code: "KR", dial_code: "+82", flag: "🇰🇷", name: "South Korea" },
  { code: "LV", dial_code: "+371", flag: "🇱🇻", name: "Latvia" },
  { code: "LT", dial_code: "+370", flag: "🇱🇹", name: "Lithuania" },
  { code: "LU", dial_code: "+352", flag: "🇱🇺", name: "Luxembourg" },
  { code: "MY", dial_code: "+60", flag: "🇲🇾", name: "Malaysia" },
  { code: "MX", dial_code: "+52", flag: "🇲🇽", name: "Mexico" },
  { code: "MA", dial_code: "+212", flag: "🇲🇦", name: "Morocco" },
  { code: "NL", dial_code: "+31", flag: "🇳🇱", name: "Netherlands" },
  { code: "NZ", dial_code: "+64", flag: "🇳🇿", name: "New Zealand" },
  { code: "NG", dial_code: "+234", flag: "🇳🇬", name: "Nigeria" },
  { code: "NO", dial_code: "+47", flag: "🇳🇴", name: "Norway" },
  { code: "PK", dial_code: "+92", flag: "🇵🇰", name: "Pakistan" },
  { code: "PE", dial_code: "+51", flag: "🇵🇪", name: "Peru" },
  { code: "PH", dial_code: "+63", flag: "🇵🇭", name: "Philippines" },
  { code: "PL", dial_code: "+48", flag: "🇵🇱", name: "Poland" },
  { code: "PT", dial_code: "+351", flag: "🇵🇹", name: "Portugal" },
  { code: "RO", dial_code: "+40", flag: "🇷🇴", name: "Romania" },
  { code: "RU", dial_code: "+7", flag: "🇷🇺", name: "Russia" },
  { code: "SA", dial_code: "+966", flag: "🇸🇦", name: "Saudi Arabia" },
  { code: "SG", dial_code: "+65", flag: "🇸🇬", name: "Singapore" },
  { code: "SK", dial_code: "+421", flag: "🇸🇰", name: "Slovakia" },
  { code: "ZA", dial_code: "+27", flag: "🇿🇦", name: "South Africa" },
  { code: "ES", dial_code: "+34", flag: "🇪🇸", name: "Spain" },
  { code: "SE", dial_code: "+46", flag: "🇸🇪", name: "Sweden" },
  { code: "CH", dial_code: "+41", flag: "🇨🇭", name: "Switzerland" },
  { code: "TH", dial_code: "+66", flag: "🇹🇭", name: "Thailand" },
  { code: "TR", dial_code: "+90", flag: "🇹🇷", name: "Turkey" },
  { code: "UA", dial_code: "+380", flag: "🇺🇦", name: "Ukraine" },
  { code: "AE", dial_code: "+971", flag: "🇦🇪", name: "United Arab Emirates" },
  { code: "GB", dial_code: "+44", flag: "🇬🇧", name: "United Kingdom" },
  { code: "US", dial_code: "+1", flag: "🇺🇸", name: "United States" },
  { code: "VN", dial_code: "+84", flag: "🇻🇳", name: "Vietnam" },
  { code: "ZW", dial_code: "+263", flag: "🇿🇼", name: "Zimbabwe" },
];
